# master.yaml
---
- hosts: masters
  remote_user: marvin
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes
  connection: ssh

  vars:
    pod_network_cidr: 192.168.0.0/16
    master_ip: 192.168.100.100
    pod_network_manifest_file: https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
    rbac_manifest_file: https://docs.projectcalico.org/v3.3/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml

  tasks:

   - name: Intilizing Kubernetes Cluster
     become_user: root
     become_method: sudo
     become: yes
     # command: kubeadm init --pod-network-cidr "{{ pod_network_cidr }}"  --apiserver-advertise-address "{{ master_ip }}"
     command: kubeadm init --control-plane-endpoint=master-node01 --pod-network-cidr=192.168.0.0/16
     run_once: true
     delegate_to: "{{ master_ip }}"

   #- pause: seconds=180

   - name: Create directory for kube config.
     become_user: marvin
     become_method: sudo
     become: yes
     file:
       path: /home/{{ansible_user }}/.kube
       state: directory
       owner: "{{ ansible_user }}"
       group: "{{ ansible_user }}"
       mode: 0755

   - name: Copy /etc/kubernetes/admin.conf to user home directory /home/{{ ansible_user }}/.kube/config.
     become_user: root
     become_method: sudo
     become: yes
     copy:
       src: /etc/kubernetes/admin.conf
       dest: /home/{{ ansible_user }}/.kube/config
       remote_src: yes
       owner: "{{ ansible_user }}"
       group: "{{ ansible_user }}"
       mode: '0644'

   - name: Remove the cache directory.
     become_user: marvin
     become_method: sudo
     become: yes
     file:
       path: /home/{{ ansible_user }}/.kube/cache
       state: absent

   - name: Create Pod Network & RBAC.
     become_user: marvin
     become_method: sudo
     become: yes
     command: "{{ item }}"
     with_items:
       #- kubectl apply -f {{ pod_network_manifest_file }}
       #- kubectl apply -f {{ rbac_manifest_file }}
       - echo "pass"

   - name: Renew certs
     become_user: root
     become_method: sudo
     become: yes
     shell: kubeadm certs renew all

   - name: Get the token for joining the nodes with Kuberentes master.
     become_user: root
     become_method: sudo
     become: yes
     shell: kubeadm token create  --print-join-command
     register: kubernetes_join_command

   - debug:
       msg: "{{ kubernetes_join_command.stdout }}"

   - name: Copy join command to local file.
     become: false
     local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777
...
